'use client'
import './globals.css'
import { Mukta } from 'next/font/google'
import Navbar from './navbar'
import Footer from './footer'

const mukta = Mukta({ 
  weight: ['300','400', '700'],
  style: ['normal'],
  display: 'swap',
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mukta.className}>
      <div className="site-wrap">
        <Navbar/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  )
}
